# application.properties

server.port=8082

# datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/finance_db
spring.datasource.username=postgres
spring.datasource.password=Sruthi123@
spring.datasource.driver-class-name=org.postgresql.Driver

# optionally tune the connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate (if you use it)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#For JWT Auth 
jwt.secret=myverylongsecretkeythatistotallysecure123andisverylongforakey!
jwt.expiration=900000
jwt.access-token.expiration=900000      
jwt.refresh-token.expiration=604800000  